juego/urls.py
"""URLS JUEGO"""
from django.urls import path
from .views import juego_trivia

urlpatterns = [
    path('', juego_trivia, name='juego'),
    #path('logout',user_logout ,name='user_logout'),
]

trivia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('juego/', include('juego.urls')),
]

usuarios/urls.py
"""URLS usuarios"""
from django.urls import path
from .views import user_login, user_logout, add_jugador

urlpatterns = [
    path('', user_login,name='user_login'),
    path('logout',user_logout ,name='user_logout'),
    path('add_jugador',add_jugador ,name='add_jugador'),
]

juego/models.py
from django.db import models
from usuarios.models import BaseModel, Jugador
# Create your models here.

# class Nivel(BaseModel):
#     nombre = models.CharField(max_length=50, unique=True)
#     aleas = models.IntegerField(default=1)

NIVEL = (
    (1, 'BASICO'),
    (2, 'MEDIO'),
    (3, 'AVANZADO'),
    (4, 'EXPERTO'),
)
class Categoria(BaseModel):
    nombre = models.CharField(max_length=60)
    
    def __str__(self) -> str:
        return f"{self.id}.{self.nombre}"
  


class Pregunta(BaseModel):
    enunciado= models.TextField()
    nivel = models.IntegerField(choices=NIVEL)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return f"{self.enunciado}, {self.nivel}, {self.categoria.nombre}"

class Respuesta(BaseModel):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    texto = models.TextField()
    es_correcta = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.pregunta.id}, {self.texto}, {self.es_correcta}"     

class ConfiguracionPartida(BaseModel):
    num_preguntas = models.IntegerField(default=1)
    tiempo_por_nivel = models.IntegerField(default=5)


class Partida(BaseModel):
    jugador = models.ForeignKey(Jugador, on_delete=models.CASCADE)
    score = models.IntegerField()
    configuracion = models.ForeignKey(ConfiguracionPartida, on_delete=models.CASCADE)

class DetallePartida():
    partida = models.ForeignKey(Partida, on_delete=models.CASCADE)
    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BaseModel(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True)
    #fecha_modificacion = models.DateTimeField(auto_now=True, null=True)
    #usuario_creacion = models.ForeignKey(User, related_name="%(class)s_creado_por", on_delete=models.SET_NULL, null=True)
    #usuario_modificacion = models.ForeignKey(User, related_name="%(class)s_modificado_por", on_delete=models.SET_NULL, null=True)
    
    class Meta:
        abstract = True

class Jugador(BaseModel):
    email = models.EmailField(unique=True)
    nombres  = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    habilitado =models.BooleanField(default=True)
    
    @property
    def nombres_completos(self):
        "Nombres completos"
        return f"{self.nombres} {self.apellidos}"
    
    def __str__(self) -> str:
        return f'{self.identificacion} {self.nombres} {self.apellidos}'

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Jugador

class LoginForm(AuthenticationForm):
    pass
    


class RegistroForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class JugadorForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Jugador
        fields = ['email', 'nombres', 'apellidos']

juego/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from juego.models import Pregunta

# Create your views here.
def juego_trivia(request):
    data = {}
    quiz_data = Pregunta.objects.all().order_by('?')[:10]
    page = 1  
    paginador = Paginator(quiz_data,1)
    preguntas = paginador.get_page(page)
    if request.method == 'POST':
      print('POST:', request.POST)
      page = request.POST.get('page')
      paginador = Paginator(quiz_data,1)
      preguntas = paginador.get_page(page)
      data['preguntas'] = preguntas 
      data['total'] = paginador.num_pages
      return render(request, 'juego/trivia.html', data)

    
    data['preguntas'] = preguntas 
    data['total'] = paginador.num_pages
    return render(request, 'juego/trivia.html', data)

usuarios/views.py
"""Vista de Votos"""
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import LoginForm, RegistroForm, JugadorForm

# Create your views here.

def user_login(request):
    """Login user"""
    print(request.method)
    context = {}
    if request.method=="POST":
        user_name = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=user_name, password=password)
        if user:   #Crear Session
            login(request, user)
            return redirect('juego')
        else:
            context["error"] = "User or Password incorrect"
            messages.error(request,"Usuario o Contraseña Incorrecta")
            return redirect('user_login')
    else:
        context['form'] = LoginForm()
        context['form_add'] = RegistroForm()
        context['form_jugador'] = JugadorForm()
        return render(request,'usuarios/login.html', context)


def user_logout(request):
    """Logout USER"""
    logout(request)
    return redirect('user_login')

def add_jugador(request):
    if request.method == 'POST':
        form = JugadorForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data['email'])
            print("Formulario")
            print("Usuario Creado")
            return redirect('user_login')
    else:
        return redirect('user_login')

templates/juego/trivia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QUIEN SABE SABE</title>
    <style>
        img{
            width: 150px;
        }
        .pregunta{
            height: 40%;
            border-bottom: 4px solid rgb(112, 110, 110);
        }
        .content{
            display: flex;
           /* align-items: center;*/
            /*justify-content: center;*/
            flex-direction: column;
            border: 4px solid rgb(56, 52, 52);
            border-radius: 10px;
            padding: 15px;
            height: 80vh;
            width: 90%;
            margin: 0 auto;
        }

        .content .pregunta{
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: center;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 2rem;
        }
    
        .respuesta {
            margin-top: 5%;
            padding:1%;
            width: 60%;
            margin: 0 auto;         
            border: 2px;
        }
        .respuesta .btn{
            text-align: center;
            margin-bottom: 0.5%;
            text-align: justify;
        }
        .btn {
            padding: 0.5rem 1rem; /* Espaciado relativo */
            font-size: 1.2em;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;

        }
        .opt{
            padding: 40px 30px;
            font-size: 1.5em;
        }
        
        .btn:hover {
            background-color: #566d56;
        }
        
        .btn:active {
            background-color: #0a0a0a;
        }
        .navegar{
            display: flex;
            justify-content: space-around;
            font-size: .3rm;
            font-weight: bold;
            margin-top: 2%;
            padding: 1%;
        }
        .navegar .btn{
            background-color: rgb(104, 100, 100);
        }
        .navegar .btn:hover{
            background-color: coral;
        }
        .temporizador{
            position: fixed;
            top: 2%;
            right: 5%;
            padding: 5px;
            border: 2px solid rgb(245, 154, 68);
            color: tomato;
            border-radius: 5px;
            font-weight: bold;
            font-size: 18pt;
            z-index: 10;
        }
    </style>
</head>
<body>
    <h1 style="text-align: center;"> QUÍEN SABE SABE</h1> <mark id='timer' class="temporizador">03:59</mark>
    <div class="content">
        {%for p in preguntas%}
        <section class="pregunta">
           <!-- <img src="https://cdn.pixabay.com/photo/2017/09/01/00/16/png-2702697_1280.png" alt="imagen">-->
            <img src="https://picsum.photos/700/400?random" alt="imagen">
            <p>{{p.enunciado}}</p>
        </section>
         <section class="respuesta"> 
            
            {%for r in p.respuesta_set.all%}
            <form action="" method="post" >
                {% csrf_token %} 
                <button type="submit" name="{{p.id}}"  class="btn" onclick="alert('click')"> {{r.texto}}
                </button>
                <input type="hidden" name="respuesta" value="{{r.id}}">
                <input type="hidden" name="pregunta" value="{{p.id}}">
                <input type="hidden" name="page" value="{{preguntas.next_page_number}}">
            </form>
            {%endfor%}
          
         </section>
    
         <nav class="navegar">
            {%if preguntas.has_previous%}
                <a class="btn" href="?page={{preguntas.previous_page_number}}"> ◀ </a>
            {%endif%}
            {%if preguntas.has_next%}
                <a class="btn" href="?page={{preguntas.next_page_number}}"> ▶ </a>
            {%endif%}
         </nav>
         
            
         {% endfor %}

         {{preguntas}}
    </div>
    <script>
        let reloj = document.getElementById('timer');
        let minutos = 0;
        let segundos = 10;
        temporizador = setInterval(()=>{
            segundos-=1;
            seg = segundos.toString().length!==2 ? `0${segundos}`:segundos    
            timer.innerText = `0${minutos}:${seg}`
            if(minutos===0 && segundos===0){
                clearInterval(temporizador);
                console.log("UNO:",getCookie('csrftoken'));
                console.log("DOS",'{{ csrf_token }}');
                fetch("/juego/",
                {
                    method:"POST",
                    body:JSON.stringify({
                        saludo: "HOLA",
                    }),
                    headers:{
                        "csrfmiddlewaretoken": '{{ csrf_token }}',    
                    },
                });
            }
            if (segundos === 0 && minutos>0){ 
                minutos -=1;
                segundos =59
            } 
        },
        1000)
        function stopTimer(){
            clearInterval(temporizador)
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        
    </script>
</body>
</html>

templates/usuarios/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style type="text/css">
        .form-login{
            background-color: beige;
            width: 50%;
            padding: 10px;
            border-radius: 10px;
            margin: 10px;
        }
    </style>
</head>
<body>
    <h1>JUEGO SABE SABE</h1>
    <div>
        <form class="form-login" action="" method="post">
            {% csrf_token %}
            <legend>LOGIN</legend>
            {{form.as_p}}
            <button type="submit">Iniciar sesión</button>
        </form>
        {%if error%}
        <div class="alert notification">
          {{error}}
        </div>
        {%endif%}
    </div>
    <!--<div>
        <form class="form-login" method="post">
            {% csrf_token %}
            {{ form_add.as_p }}
            <button type="submit">Registrarse</button>
        </form>
    </div>-->

    <div>
        <form class="form-login" action="{%url 'add_jugador'%}" method="post" autocomplete="off">
            {% csrf_token %}
            {{ form_jugador.as_p }}
            <button type="submit">Crear</button>
        </form>
    </div>
</body>
</html>